# Generated by Django 5.1.15 on 2026-09-22 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('lb', 'lb'), ('kg', 'kg')], default='lb', max_length=2)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('muscle_group', models.CharField(blank=True, max_length=80)),
                ('equipment', models.CharField(blank=True, max_length=80)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('serving_description', models.CharField(default='1 serving', max_length=120)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_at', models.DateTimeField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=16)),
                ('serving_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('name_snapshot', models.CharField(max_length=160)),
                ('calories_snapshot', models.PositiveIntegerField()),
                ('protein_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carbs_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tracker.food')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calorie_goal', models.PositiveIntegerField(default=2800)),
                ('protein_goal', models.PositiveIntegerField(default=180)),
                ('carb_goal', models.PositiveIntegerField(default=300)),
                ('fat_goal', models.PositiveIntegerField(default=80)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preferred_weight_unit', models.CharField(choices=[('lb', 'lb'), ('kg', 'kg')], default='lb', max_length=2)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Workout', max_length=160)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('import_source', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='tracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='tracker.workout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight_unit', models.CharField(default='lb', max_length=8)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set_type', models.CharField(choices=[('working', 'Working'), ('warmup', 'Warmup'), ('drop', 'Drop'), ('failure', 'Failure')], default='working', max_length=16)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
                'constraints': [models.UniqueConstraint(fields=('workout_exercise', 'set_number'), name='unique_set_number')],
            },
        ),
    ]
