# Generated by Django 5.2.17 on 2026-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_notes_import_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('serving_description', models.CharField(default='1 serving', max_length=120)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=16)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
