# Generated by Django 5.2.17 on 2026-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_savedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='label_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='nutrition_source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='serving_description_snapshot',
            field=models.CharField(default='1 serving', max_length=120),
        ),
    ]
